//package model;
//// Generated Nov 1, 2020 4:29:39 PM by Hibernate Tools 4.3.5.Final
//
//import java.io.Serializable;
//import java.util.HashSet;
//import java.util.Set;
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.FetchType;
//import javax.persistence.GeneratedValue;
//import static javax.persistence.GenerationType.IDENTITY;
//import javax.persistence.Id;
//import javax.persistence.OneToMany;
//import javax.persistence.Table;
//import javax.persistence.Transient;
//
//import org.springframework.web.multipart.MultipartFile;
//
///**
// * Brand generated by hbm2java
// */
//@Entity
//@Table(name = "Brand")
//public class Brand implements java.io.Serializable {
//
//	private Integer brandId;
//	private String brandname;
//	private boolean status;
//	private MultipartFile brandImg;
//
//	@Transient
//	public MultipartFile getBrandImg() {
//		return brandImg;
//	}
//
//	public void setBrandImg(MultipartFile brandImg) {
//		this.brandImg = brandImg;
//	}
//
//	private Set<Product> products = new HashSet<Product>(0);
//
//	public Brand() {
//	}
//
//	public Brand(String brandname, boolean status) {
//		this.brandname = brandname;
//		this.status = status;
//	}
//
//	public Brand(boolean status) {
//		super();
//		this.status = status;
//	}
//
//	public Brand(String brandname, MultipartFile brandImg, boolean status, Set<Product> products) {
//		this.brandname = brandname;
//		this.status = status;
//		this.brandImg = brandImg;
//		this.products = products;
//	}
//
//	@Id
//	@GeneratedValue(strategy = IDENTITY)
//
//	@Column(name = "Brand_ID", unique = true, nullable = false)
//	public Integer getBrandId() {
//		return this.brandId;
//	}
//
//	public void setBrandId(Integer brandId) {
//		this.brandId = brandId;
//	}
//
//	@Column(name = "Brandname", nullable = false)
//	public String getBrandname() {
//		return this.brandname;
//	}
//
//	public void setBrandname(String brandname) {
//		this.brandname = brandname;
//	}
//
//	@Column(name = "Status", nullable = false)
//	public boolean isStatus() {
//		return this.status;
//	}
//
//	public void setStatus(boolean status) {
//		this.status = status;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "brand")
//	public Set<Product> getProducts() {
//		return this.products;
//	}
//
//	public void setProducts(Set<Product> products) {
//		this.products = products;
//	}
//
//	@Override
//	public String toString() {
//		return "Brand [brandId=" + brandId + ", brandname=" + brandname + ", status=" + status + ", products="
//				+ products + "]";
//	}
//
//}
